package com.markmolenmaker.dioninsanity.backend.models.cluebingo;

import java.util.Random;

public enum EItem {
    AHRIMS_HOOD, AHRIMS_ROBETOP, AHRIMS_ROBESKIRT, AHRIMS_STAFF,
    DHAROKS_HELM, DHAROKS_PLATEBODY, DHAROKS_PLATELEGS, DHAROKS_GREATAXE,
    GUTHANS_HELM, GUTHANS_PLATEBODY, GUTHANS_CHAINSKIRT, GUTHANS_WARSPEAR,
    KARILS_COIF, KARILS_LEATHERTOP, KARILS_LEATHERSKIRT, KARILS_CROSSBOW,
    TORAGS_HELM, TORAGS_PLATEBODY, TORAGS_PLATELEGS, TORAGS_HAMMERS,
    VERACS_HELM, VERACS_BRASSARD, VERACS_PLATESKIRT, VERACS_FLAIL,
    MIND_RUNE, CHAOS_RUNE, DEATH_RUNE, BLOOD_RUNE, BOLT_RACK,
    LOOP_HALF_OF_KEY, TOOTH_HALF_OF_KEY, DRAGON_MED_HELM, COINS, CLUE_SCROLL;

    private static final Random PRNG = new Random();

    public static EItem getRandomEItem() {
        EItem[] items = values();
        return items[PRNG.nextInt(items.length)];
    }
}
